package com.example.android.muicapp.models

enum class CategoryID {
    BUTTONS,
    SLIDERS,
    NOTIFICATION,
    BOTTOM_NAVIGATION
}

enum class ActionID {
    BUTTONS_BASIC,
    BUTTONS_CUSTOM,
    BUTTONS_FAB,
    SLIDERS_LIGHT,
    SLIDERS_DARK,
    SLIDERS_SWITCH,
    NOTIFICATION_BASIC,
    NOTIFICATION_TOASTS,
    NOTIFICATION_SNACKS,
    BOTTOM_NAVIGATION_SIMPLE,
    BOTTOM_NAVIGATION_FAB,
    BOTTOM_NAVIGATION_CUSTOM
}